// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5_7WMxcnBsqagXG0_vVy3vAAd6aeVAtM',
    appId: '1:733953602039:web:4aaac84f19c008212dbef2',
    messagingSenderId: '733953602039',
    projectId: 'fluxchatoai',
    authDomain: 'fluxchatoai.firebaseapp.com',
    storageBucket: 'fluxchatoai.appspot.com',
    measurementId: 'G-YRBX82886H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPg0efcBFmB4XygOCNEP4lojxKqqE7-RA',
    appId: '1:733953602039:android:1882b166556822232dbef2',
    messagingSenderId: '733953602039',
    projectId: 'fluxchatoai',
    storageBucket: 'fluxchatoai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO9S8SWHUqQYpyl17V2SdzmetF0sCKyBs',
    appId: '1:733953602039:ios:2951039841feebb52dbef2',
    messagingSenderId: '733953602039',
    projectId: 'fluxchatoai',
    storageBucket: 'fluxchatoai.appspot.com',
    iosClientId: '733953602039-gdfsvipf8g5pjrgacrmem52fiqn95gos.apps.googleusercontent.com',
    iosBundleId: 'com.kodfluxchatoai.fluxchatoai',
  );
}
